### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rjc** [mattiasgeniar/certdiff#2]
Hi Mattias,

A couple of weeks ago I was looking at a license-related issue (GPLv3 as well) and the same problem exists here - your main source file doesn't mention what license it is covered by and including just the license file in the repository is not enough:

https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude
https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly

Since the license itself is > 600 lines and your shell script < 50, wouldn't it make more sense to license it under a permissive license, i.e. MIT/X11, BSD or ISC? Even FSF acknowledges that:

https://www.gnu.org/licenses/gpl-faq.html#WhatIfWorkIsShort

Kind regards,

Raf

**Comment by mattiasgeniar** [comment]
I should have a closer look at all those licenses, it appears.

I had assumed "just dropping the license file" would be sufficient. :-)

**Comment by rjc** [comment]
One would think ;^)

My take on it is - if I don't understand it without asking a lawyer, then it's a **no** from me.

Also, all the licenses I've mentioned above fit in a single terminal window... without scrolling! :^D

https://opensource.org/licenses/BSD-2-Clause
https://opensource.org/licenses/MIT
https://opensource.org/licenses/ISC # my personal preference

Regards,

Raf

**Comment by mattiasgeniar** [comment]
I made an explicit reference to the license and changed it to the much simpeler MIT one. Thanks for the heads-up, I learned something new here!
